name: hcp-crm-interaction-manager

services:
  postgres:
    image: postgres:16-alpine
    container_name: hcp_crm_postgres
    environment:
      POSTGRES_USER: hcp_user
      POSTGRES_PASSWORD: hcp_password
      POSTGRES_DB: hcp_crm
    ports:
      - '5433:5432'
    volumes:
      - hcp_crm_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hcp_user -d hcp_crm']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  hcp_crm_pg_data:
